require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GraffitisController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Graffiti. As you add validations to Graffiti, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GraffitisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all graffitis as @graffitis" do
      graffiti = Graffiti.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:graffitis)).to eq([graffiti])
    end
  end

  describe "GET show" do
    it "assigns the requested graffiti as @graffiti" do
      graffiti = Graffiti.create! valid_attributes
      get :show, {:id => graffiti.to_param}, valid_session
      expect(assigns(:graffiti)).to eq(graffiti)
    end
  end

  describe "GET new" do
    it "assigns a new graffiti as @graffiti" do
      get :new, {}, valid_session
      expect(assigns(:graffiti)).to be_a_new(Graffiti)
    end
  end

  describe "GET edit" do
    it "assigns the requested graffiti as @graffiti" do
      graffiti = Graffiti.create! valid_attributes
      get :edit, {:id => graffiti.to_param}, valid_session
      expect(assigns(:graffiti)).to eq(graffiti)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Graffiti" do
        expect {
          post :create, {:graffiti => valid_attributes}, valid_session
        }.to change(Graffiti, :count).by(1)
      end

      it "assigns a newly created graffiti as @graffiti" do
        post :create, {:graffiti => valid_attributes}, valid_session
        expect(assigns(:graffiti)).to be_a(Graffiti)
        expect(assigns(:graffiti)).to be_persisted
      end

      it "redirects to the created graffiti" do
        post :create, {:graffiti => valid_attributes}, valid_session
        expect(response).to redirect_to(Graffiti.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved graffiti as @graffiti" do
        post :create, {:graffiti => invalid_attributes}, valid_session
        expect(assigns(:graffiti)).to be_a_new(Graffiti)
      end

      it "re-renders the 'new' template" do
        post :create, {:graffiti => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested graffiti" do
        graffiti = Graffiti.create! valid_attributes
        put :update, {:id => graffiti.to_param, :graffiti => new_attributes}, valid_session
        graffiti.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested graffiti as @graffiti" do
        graffiti = Graffiti.create! valid_attributes
        put :update, {:id => graffiti.to_param, :graffiti => valid_attributes}, valid_session
        expect(assigns(:graffiti)).to eq(graffiti)
      end

      it "redirects to the graffiti" do
        graffiti = Graffiti.create! valid_attributes
        put :update, {:id => graffiti.to_param, :graffiti => valid_attributes}, valid_session
        expect(response).to redirect_to(graffiti)
      end
    end

    describe "with invalid params" do
      it "assigns the graffiti as @graffiti" do
        graffiti = Graffiti.create! valid_attributes
        put :update, {:id => graffiti.to_param, :graffiti => invalid_attributes}, valid_session
        expect(assigns(:graffiti)).to eq(graffiti)
      end

      it "re-renders the 'edit' template" do
        graffiti = Graffiti.create! valid_attributes
        put :update, {:id => graffiti.to_param, :graffiti => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested graffiti" do
      graffiti = Graffiti.create! valid_attributes
      expect {
        delete :destroy, {:id => graffiti.to_param}, valid_session
      }.to change(Graffiti, :count).by(-1)
    end

    it "redirects to the graffitis list" do
      graffiti = Graffiti.create! valid_attributes
      delete :destroy, {:id => graffiti.to_param}, valid_session
      expect(response).to redirect_to(graffitis_url)
    end
  end

end
